FROM python:3.9-slim

# CORRECCIÓN: Cambiamos 'libgl1-mesa-glx' por 'libgl1'
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
# -u para ver logs de python en tiempo real
CMD ["python", "-u", "main.py"]